// packages/svelte/src/node-property-panel/hint.svelte
<script lang="ts">
    import { InfoIcon } from 'phosphor-svelte';
    import Tooltip from '../tooltip.svelte';
    import './inspectors.css';

    let { text }: { text: string } = $props();
</script>

<Tooltip {text}>
    <button type="button" class="inspector-hint" data-testid="hint" aria-label={text}>
        <InfoIcon size={12} weight="fill" />
    </button>
</Tooltip>

// packages/react/src/node-property-panel/inspectors/hint.tsx
import { InfoIcon } from '@phosphor-icons/react';
import { Tooltip } from '../../tooltip.tsx';
import css from './inspectors.module.css';

/** Explains a control or value. The tooltip is the whole behavior; clicking does nothing. */
export function Hint({ text }: { text: string }) {
  return (
    <Tooltip text={text}>
      <button type="button" className={css.hint} data-testid="hint" aria-label={text}>
        <InfoIcon size={12} weight="fill" />
      </button>
    </Tooltip>
  );
}
