// packages/svelte/src/node-property-panel/quantization-inspector.svelte
<script lang="ts">
  import { inspectWeightQuantization } from '@wetron/core/weight-quantization';
  import { formatVal } from '@wetron/core/format-val';
  import { quantizationHint } from '@wetron/core/inspector-hints';
  import { getWeightInspection } from './weight-inspection-context.ts';
  import Hint from './hint.svelte';
  import './inspectors.css';
  const context = getWeightInspection();
  const inspection = $derived(context.current);
  const result = $derived(
    inspection.bytes ? inspectWeightQuantization(inspection.bytes, inspection.tensor.dtype ?? '') : null,
  );
  let blockIndex = $state(0);
  const index = $derived(result ? Math.min(blockIndex, Math.max(0, result.blockCount - 1)) : 0);
  const block = $derived(result?.blockAt(index) ?? null);
  const maximum = $derived(result ? Math.max(...result.frequencies, 1) : 1);
</script>

<div class="inspector" data-testid="quantization-inspector">
  {#if !result}<div class="inspector-note">
      Decoded values are available, but encoded quantization diagnostics are not implemented for this dtype.
    </div>{:else}<div class="inspector-controls">
      <div class="inspector-control">
        <span class="inspector-caption">block <Hint text={quantizationHint('block', result, block)} /></span><span
          class="inspector-bounded"
          ><input
            class="inspector-field"
            aria-label="Quantization block"
            type="number"
            min="0"
            max={Math.max(0, result.blockCount - 1)}
            value={index}
            oninput={(event) =>
              (blockIndex = Math.max(0, Math.min(result.blockCount - 1, Number(event.currentTarget.value))))}
          /><span class="inspector-bound" data-testid="quantization-block"
            >of {(result.blockCount - 1).toLocaleString()}</span
          ></span
        >
      </div>
    </div>
    <div class="inspector-plot">
      <div class="inspector-bars">
        {#each result.frequencies as count, code}<span
            title="code {code} · {count}"
            style="height: {Math.max(2, (count / maximum) * 100)}%"
          ></span>{/each}
      </div>
      <div class="inspector-chart-axis">
        <span>code 0</span><span>code 8 · zero <Hint text={quantizationHint('histogram', result, block)} /></span><span
          >code {result.frequencies.length - 1}</span
        >
      </div>
    </div>
    <div class="inspector-stats">
      <span class="inspector-stat"
        ><span class="inspector-stat-label">format <Hint text={quantizationHint('format', result, block)} /></span><span
          class="inspector-stat-value"
          data-testid="quantization-format">{result.dtype}</span
        ></span
      ><span class="inspector-stat"
        ><span class="inspector-stat-label">levels used <Hint text={quantizationHint('levels', result, block)} /></span
        ><span class="inspector-stat-value" data-testid="quantization-levels"
          >{result.frequencies.filter(Boolean).length}/{result.frequencies.length}</span
        ></span
      ><span class="inspector-stat"
        ><span class="inspector-stat-label"
          >block size <Hint text={quantizationHint('blockSize', result, block)} /></span
        ><span class="inspector-stat-value" data-testid="quantization-blockSize">{result.valuesPerBlock}</span></span
      ><span class="inspector-stat"
        ><span class="inspector-stat-label"
          >trailing bytes <Hint text={quantizationHint('trailingBytes', result, block)} /></span
        ><span class="inspector-stat-value" data-testid="quantization-trailingBytes">{result.trailingBytes}</span></span
      >{#if block}<span class="inspector-stat"
          ><span class="inspector-stat-label">scale <Hint text={quantizationHint('scale', result, block)} /></span><span
            class="inspector-stat-value"
            data-testid="quantization-scale">{formatVal(block.scale, 'float32')}</span
          ></span
        ><span class="inspector-stat"
          ><span class="inspector-stat-label"
            >saturation <Hint text={quantizationHint('saturation', result, block)} /></span
          ><span class="inspector-stat-value" data-testid="quantization-saturation"
            >{block.saturation} / {result.valuesPerBlock}</span
          ></span
        ><span class="inspector-stat"
          ><span class="inspector-stat-label"
            >zero code <Hint text={quantizationHint('zeroCode', result, block)} /></span
          ><span class="inspector-stat-value" data-testid="quantization-zeroCode">{block.zeroCodeFrequency}</span></span
        >{/if}
    </div>{/if}
</div>

// packages/react/src/node-property-panel/inspectors/quantization-inspector.tsx
import { useMemo, useState } from 'react';
import { inspectWeightQuantization } from '@wetron/core/weight-quantization';
import { formatVal } from '@wetron/core/format-val';
import { quantizationHint } from '@wetron/core/inspector-hints';
import { useWeightInspection } from '../weight-inspection-context.tsx';
import { Hint } from './hint.tsx';
import css from './inspectors.module.css';

export function QuantizationInspector() {
  const inspection = useWeightInspection();
  const result = useMemo(
    () => (inspection.bytes ? inspectWeightQuantization(inspection.bytes, inspection.tensor.dtype ?? '') : null),
    [inspection],
  );
  const [blockIndex, setBlockIndex] = useState(0);
  if (!result)
    return (
      <div className={css.root} data-testid="quantization-inspector">
        <div className={css.note}>
          Decoded values are available, but encoded quantization diagnostics are not implemented for this dtype.
        </div>
      </div>
    );
  const index = Math.min(blockIndex, Math.max(0, result.blockCount - 1));
  const block = result.blockAt(index);
  const max = Math.max(...result.frequencies, 1);
  const stat = (label: string, value: string, field: Parameters<typeof quantizationHint>[0]) => (
    <span className={css.stat} key={label}>
      <span className={css.statLabel}>
        {label} <Hint text={quantizationHint(field, result, block)} />
      </span>
      <span className={css.statValue} data-testid={`quantization-${field}`}>
        {value}
      </span>
    </span>
  );
  return (
    <div className={css.root} data-testid="quantization-inspector">
      <div className={css.controls}>
        <div className={css.control}>
          <span className={css.caption}>
            block <Hint text={quantizationHint('block', result, block)} />
          </span>
          <span className={css.bounded}>
            <input
              className={css.field}
              aria-label="Quantization block"
              type="number"
              min={0}
              max={Math.max(0, result.blockCount - 1)}
              value={index}
              onChange={(event) =>
                setBlockIndex(Math.max(0, Math.min(result.blockCount - 1, Number(event.target.value))))
              }
            />
            <span className={css.bound} data-testid="quantization-block">
              of {(result.blockCount - 1).toLocaleString()}
            </span>
          </span>
        </div>
      </div>
      <div className={css.plot}>
        <div className={css.bars}>
          {result.frequencies.map((count, code) => (
            <span
              key={code}
              title={`code ${code} · ${count}`}
              style={{ height: `${Math.max(2, (count / max) * 100)}%` }}
            />
          ))}
        </div>
        <div className={css.chartAxis}>
          <span>code 0</span>
          <span>
            code 8 · zero <Hint text={quantizationHint('histogram', result, block)} />
          </span>
          <span>code {result.frequencies.length - 1}</span>
        </div>
      </div>
      <div className={css.stats}>
        {stat('format', result.dtype, 'format')}
        {stat('levels used', `${result.frequencies.filter(Boolean).length}/${result.frequencies.length}`, 'levels')}
        {stat('block size', String(result.valuesPerBlock), 'blockSize')}
        {stat('trailing bytes', String(result.trailingBytes), 'trailingBytes')}
        {block && stat('scale', formatVal(block.scale, 'float32'), 'scale')}
        {block && stat('saturation', `${block.saturation} / ${result.valuesPerBlock}`, 'saturation')}
        {block && stat('zero code', String(block.zeroCodeFrequency), 'zeroCode')}
      </div>
    </div>
  );
}
