// packages/svelte/src/node-property-panel/values-inspector.svelte
<script lang="ts">
    import { formatVal, isIntegerDtype } from '@wetron/core/format-val';
    import { getWeightInspection } from './weight-inspection-context.ts';
    import VirtualValues from './virtual-values.svelte';
    import './inspectors.css';
    const context = getWeightInspection();
    const ready = $derived(context.current.status === 'ready' ? context.current : null);
    const dtype = $derived(ready?.tensor.dtype ?? 'float32');
</script>

{#if ready}<div class="inspector" data-testid="values-inspector">
        <div class="inspector-note">{ready.values.length.toLocaleString()} flattened values</div>
        <VirtualValues
            values={ready.values}
            format={(value: number | bigint) =>
                typeof value === 'bigint' ? value.toString() : formatVal(value, dtype)}
            align={isIntegerDtype(dtype) ? 'center' : 'right'}
        />
    </div>{/if}

// packages/react/src/node-property-panel/inspectors/values-inspector.tsx
import { formatVal, isIntegerDtype } from "@wetron/core/format-val";
import { useWeightInspection } from "../weight-inspection-context.tsx";
import { VirtualValues } from "../virtual-values/virtual-values.tsx";
import css from "./inspectors.module.css";

export function ValuesInspector() {
  const inspection = useWeightInspection();
  if (inspection.status !== "ready") return null;
  const dtype = inspection.tensor.dtype ?? "float32";
  return (
    <div className={css.root} data-testid="values-inspector">
      <div className={css.note}>{inspection.values.length.toLocaleString()} flattened values</div>
      <VirtualValues
        data-testid="values-grid"
        values={inspection.values}
        format={(value) => (typeof value === "bigint" ? value.toString() : formatVal(value, dtype))}
        align={isIntegerDtype(dtype) ? "center" : "right"}
      />
    </div>
  );
}
