// packages/react/src/nodes/graph-node.tsx
import React from "react";
import type { Node, NodeProps } from "@xyflow/react";
import type { GraphNodeData } from "@wetron/core/transform";
import { opCategory } from "@wetron/core";
import { CATEGORY_THEME, CATEGORY_ICON } from "../theme.ts";
import { useColorMode } from "../color-mode-context.ts";
import { NodeCard } from "./node-card/node-card.tsx";
import css from "./node-card/node-card.module.css";

export function GraphNodeComponent({ data, selected }: NodeProps<Node<GraphNodeData>>) {
  const isDark = useColorMode() === "dark";
  const cat = opCategory(data.opType);
  const theme = CATEGORY_THEME[cat];
  const color = isDark ? theme.dark : theme.light;
  const hasWeights = data.weightInputs != null && data.weightInputs.length > 0;
  return (
    <NodeCard
      nodeType="graphNode"
      topHandle
      bottomHandle
      pill={data.opType}
      subtitle={data.name && !/^op_\d+$/.test(data.name) ? data.name : undefined}
      cat={cat}
      iconEntry={CATEGORY_ICON[cat]}
      tinted={!hasWeights}
      selected={selected}
      colors={{
        color,
        bg: isDark ? "#1e1e2e" : "#fff",
        border: isDark ? "#333" : "#e0e0e0",
        muted: isDark ? "#7a7a9a" : "#999",
        tintBase: isDark ? "#1e1e2e" : "white",
      }}
    >
      {data.weightInputs && data.weightInputs.length > 0
        ? data.weightInputs.map((w, i) => (
            <div
              key={w.name}
              className={css.weightRow}
              data-weight-name={w.name}
              data-weight-dtype={w.dtype}
              data-weight-shape={w.shape.join(",")}
            >
              <span className={css.weightLabel}>{w.label}</span>
              <span className={css.weightShape}>〈{w.shape.join("×")}〉</span>
            </div>
          ))
        : null}
    </NodeCard>
  );
}

// packages/svelte/src/nodes/graph-node.svelte
<script lang="ts">
  import type { GraphNodeData } from '@wetron/core/transform';
  import { opCategory } from '@wetron/core';
  import { CATEGORY_THEME } from '../theme.ts';
  import { consumeColorMode } from '../color-mode-context.ts';
  import NodeCard from './node-card.svelte';

  let { data, selected = false }: { data: GraphNodeData; selected?: boolean } = $props();

  const isDark = $derived(consumeColorMode() === 'dark');
  const cat = $derived(opCategory(data.opType));
  const theme = $derived(CATEGORY_THEME[cat]);
  const color = $derived(isDark ? theme.dark : theme.light);
  const hasWeights = $derived(data.weightInputs != null && data.weightInputs.length > 0);
</script>

<NodeCard
  nodeType="graphNode"
  topHandle
  bottomHandle
  pill={data.opType}
  subtitle={data.name && !/^op_\d+$/.test(data.name) ? data.name : undefined}
  {cat}
  {color}
  bg={isDark ? '#1e1e2e' : '#fff'}
  border={isDark ? '#333' : '#e0e0e0'}
  muted={isDark ? '#7a7a9a' : '#999'}
  tintBase={isDark ? '#1e1e2e' : 'white'}
  tinted={!hasWeights}
  {selected}
>
  {#if hasWeights && data.weightInputs}
    {#each data.weightInputs as w}
      <div
        class="weight-row"
        data-weight-name={w.name}
        data-weight-dtype={w.dtype}
        data-weight-shape={w.shape.join(',')}
      >
        <span class="weight-label">{w.label}</span>
        <span class="weight-shape">〈{w.shape.join('×')}〉</span>
      </div>
    {/each}
  {/if}
</NodeCard>

<style>
  .weight-row {
    display: flex;
    gap: 4px;
    font-size: 10px;
    color: var(--node-muted);
    margin-top: 3px;
    border-radius: 2px;
    padding: 2px 3px;
    cursor: pointer;
    transition: background 0.1s;
  }
  .weight-row:hover {
    background: color-mix(in oklch, var(--node-color) 12%, transparent);
  }
  .weight-label {
    font-weight: 600;
    color: var(--node-color);
    min-width: 14px;
  }
  .weight-shape {
    opacity: 0.85;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>
