// packages/react/src/nodes/node-card/node-card.tsx
import React from 'react';
import { Handle, Position } from '@xyflow/react';
import { CaretRightIcon } from '@phosphor-icons/react';
import type { OpCategory } from '@wetron/core/categories';
import type { IconEntry } from '../../theme.ts';
import { Tooltip } from '../../tooltip.tsx';
import css from './node-card.module.css';

type CardColors = {
  color: string;
};

export function NodeCard({
  nodeType,
  topHandle = false,
  bottomHandle = false,
  pill,
  subtitle,
  cat,
  iconEntry,
  colors,
  tinted = false,
  selected = false,
  ariaLabel,
  children,
  scopeName,
  onOpenScope,
}: {
  nodeType: 'graphNode' | 'ioNode';
  topHandle?: boolean;
  bottomHandle?: boolean;
  pill: string;
  subtitle?: string;
  cat: OpCategory;
  iconEntry: IconEntry;
  colors: CardColors;
  tinted?: boolean;
  selected?: boolean;
  ariaLabel?: string;
  children?: React.ReactNode;
  scopeName?: string;
  onOpenScope?: (e: React.MouseEvent) => void;
}) {
  return (
    <div
      role="button"
      aria-label={ariaLabel ?? pill}
      aria-pressed={selected}
      data-nodetype={nodeType}
      className={`${css.card}${tinted ? ` ${css.cardTinted}` : ''}`}
      style={
        {
          '--node-color': colors.color,
          ...(selected
            ? {
                borderColor: colors.color,
                boxShadow: `0 0 0 2px color-mix(in oklch, ${colors.color} 25%, transparent), 0 1px 4px rgba(0,0,0,0.08)`,
              }
            : {}),
        } as React.CSSProperties
      }
    >
      {topHandle && <Handle type="target" position={Position.Top} />}
      <div className={css.headerRow}>
        <Tooltip text={pill} onlyIfOverflow>
          <span className={css.pill}>{pill}</span>
        </Tooltip>
        <span data-icon={cat} className={css.icon}>
          {iconEntry.kind === 'glyph' ? (
            <span className={css.glyph}>{iconEntry.char}</span>
          ) : (
            <iconEntry.Component size={16} color="currentColor" />
          )}
        </span>
      </div>
      {scopeName ? (
        onOpenScope ? (
          <button
            type="button"
            className={css.scopeRow}
            onClick={onOpenScope}
            aria-label={`Open ${scopeName} sub-graph`}
          >
            <Tooltip text={scopeName} onlyIfOverflow>
              <span className={css.scopeName}>{scopeName}</span>
            </Tooltip>
            <span className={css.scopeChev} aria-hidden="true">
              <CaretRightIcon size={12} weight="bold" />
            </span>
          </button>
        ) : (
          <div className={css.scopeRow}>
            <Tooltip text={scopeName} onlyIfOverflow>
              <span className={css.scopeName}>{scopeName}</span>
            </Tooltip>
            <span className={css.scopeChev} aria-hidden="true">
              <CaretRightIcon size={12} weight="bold" />
            </span>
          </div>
        )
      ) : (
        subtitle && (
          <Tooltip text={subtitle} onlyIfOverflow>
            <span className={css.subtitle}>{subtitle}</span>
          </Tooltip>
        )
      )}
      {React.Children.toArray(children).some(Boolean) && (
        <div data-nodename className={css.meta}>
          {children}
        </div>
      )}
      {bottomHandle && <Handle type="source" position={Position.Bottom} />}
    </div>
  );
}

// packages/svelte/src/nodes/node-card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { Handle, Position } from '@xyflow/svelte';
  import { CaretRightIcon } from 'phosphor-svelte';
  import type { OpCategory } from '@wetron/core/categories';
  import CategoryIcon from './category-icon.svelte';
  import Tooltip from '../tooltip.svelte';

  interface Props {
    nodeType: 'graphNode' | 'ioNode';
    topHandle?: boolean;
    bottomHandle?: boolean;
    pill: string;
    subtitle?: string;
    ariaLabel?: string;
    cat: OpCategory;
    op?: string;
    color: string;
    bg: string;
    border: string;
    muted: string;
    tintBase?: string;
    tinted?: boolean;
    selected?: boolean;
    children?: Snippet;
    scopeName?: string;
    onOpenScope?: (e: MouseEvent) => void;
  }

  let {
    nodeType,
    topHandle = false,
    bottomHandle = false,
    pill,
    subtitle,
    ariaLabel,
    cat,
    op,
    color,
    bg,
    border,
    muted,
    tintBase = 'white',
    tinted = false,
    selected = false,
    children,
    scopeName,
    onOpenScope,
  }: Props = $props();

  const cardBg = $derived(tinted ? `color-mix(in oklch, ${color} 20%, ${tintBase})` : bg);
  const cardBorder = $derived(selected ? color : tinted ? `color-mix(in oklch, ${color} 38%, ${tintBase})` : border);
  const selectedShadow = $derived(
    selected ? `0 0 0 2px color-mix(in oklch, ${color} 25%, transparent), 0 1px 4px rgba(0,0,0,0.08)` : undefined,
  );
</script>

<div
  role="button"
  aria-label={ariaLabel ?? pill}
  aria-pressed={selected}
  data-nodetype={nodeType}
  class="card"
  style:background={cardBg}
  style:border="1px solid {cardBorder}"
  style:box-shadow={selectedShadow}
  style:--node-color={color}
  style:--node-muted={muted}
>
  {#if topHandle}
    <Handle type="target" position={Position.Top} />
  {/if}
  <div class="header-row">
    <Tooltip text={pill} onlyIfOverflow>
      <span class="pill">{pill}</span>
    </Tooltip>
    <span class="icon">
      <CategoryIcon {cat} {op} size={16} />
    </span>
  </div>
  {#if scopeName}
    {#if onOpenScope}
      <button type="button" class="scope-row" onclick={onOpenScope} aria-label="Open {scopeName} sub-graph">
        <Tooltip text={scopeName} onlyIfOverflow>
          <span class="scope-name">{scopeName}</span>
        </Tooltip>
        <CaretRightIcon size={12} weight="bold" />
      </button>
    {:else}
      <div class="scope-row">
        <Tooltip text={scopeName} onlyIfOverflow>
          <span class="scope-name">{scopeName}</span>
        </Tooltip>
        <CaretRightIcon size={12} weight="bold" />
      </div>
    {/if}
  {:else if subtitle}
    <Tooltip text={subtitle} onlyIfOverflow>
      <div class="subtitle">{subtitle}</div>
    </Tooltip>
  {/if}
  {@render children?.()}
  {#if bottomHandle}
    <Handle type="source" position={Position.Bottom} />
  {/if}
</div>

<style>
  .card {
    position: relative;
    padding: 7px 8px;
    border-radius: 4px;
    width: 220px; /* must match NODE_W in transform.ts */
    box-sizing: border-box;
    line-height: 1;
    cursor: pointer;
    box-shadow: 0 1px 4px rgba(0, 0, 0, 0.08);
    transition:
      box-shadow 0.12s,
      border-color 0.12s;
    /* defensive resets against consumer CSS resets */
    font-family: monospace;
    font-size: 13px;
    text-align: left;
    letter-spacing: normal;
    word-spacing: normal;
    border-style: solid;
  }

  .card:hover {
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.13);
  }

  .header-row {
    display: flex;
    align-items: center;
    gap: 6px;
    overflow: hidden;
  }

  .pill {
    font-family: monospace;
    font-size: 13px;
    font-weight: 700;
    white-space: nowrap;
    color: var(--node-color);
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .icon {
    display: flex;
    align-items: center;
    flex-shrink: 0;
    margin-left: auto;
    color: color-mix(in oklch, var(--node-color) 70%, transparent);
  }

  .subtitle {
    display: inline-block;
    max-width: 100%;
    font-size: 11px;
    color: var(--node-muted);
    margin-top: 2px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-family: monospace;
  }

  .scope-row {
    display: flex;
    align-items: center;
    gap: 6px;
    margin: 5px -8px -7px;
    padding: 6px 10px;
    background: color-mix(in oklch, var(--node-color) 18%, transparent);
    color: var(--node-color);
    font-family: ui-monospace, Menlo, monospace;
    font-size: 11px;
    border: none;
    border-radius: 0 0 3px 3px;
    cursor: pointer;
    width: calc(100% + 16px);
    text-align: left;
    transition: background 0.12s;
  }

  .scope-row:hover {
    background: color-mix(in oklch, var(--node-color) 28%, transparent);
  }

  .scope-row:focus-visible {
    outline: 2px solid var(--node-color);
    outline-offset: -2px;
  }

  .scope-name {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    opacity: 0.85;
  }
</style>
