// packages/svelte/src/node-property-panel/virtual-values.svelte
<script lang="ts">
  import { createVirtualizer } from '@tanstack/svelte-virtual';

  type Values = Float64Array | Int32Array | BigInt64Array;

  let { values, format, align = 'center' }: {
    values: Values;
    format: (v: number) => string;
    align?: 'center' | 'right';
  } = $props();

  const ROW_HEIGHT = 16;
  const COLS = 5;

  let parentRef = $state<HTMLDivElement | null>(null);

  const totalRows = $derived(Math.ceil(values.length / COLS));

  const virtualizer = $derived(
    createVirtualizer<HTMLDivElement, HTMLDivElement>({
      count: totalRows,
      getScrollElement: () => parentRef,
      estimateSize: () => ROW_HEIGHT,
      overscan: 6,
    }),
  );

  const items = $derived($virtualizer.getVirtualItems());
  const totalSize = $derived($virtualizer.getTotalSize());
</script>

<div bind:this={parentRef} class="scroll" data-testid="values-grid">
  <div class="grid" style="height: {totalSize}px; position: relative;">
    {#each items as row (row.index)}
      <div
        class="row {align === 'right' ? 'alignRight' : 'alignCenter'}"
        style="position: absolute; top: {row.start}px; left: 0; right: 0; height: {ROW_HEIGHT}px;"
      >
        {#each Array.from({ length: COLS }, (_, c) => c) as c (c)}
          {@const idx = row.index * COLS + c}
          {#if idx < values.length}
            {@const raw = values[idx]}
            {@const num = typeof raw === 'bigint' ? Number(raw) : raw}
            <span>{format(num)}</span>
          {:else}
            <span></span>
          {/if}
        {/each}
      </div>
    {/each}
  </div>
</div>

<style>
  .scroll {
    max-height: 300px;
    overflow-y: auto;
    font-variant-numeric: tabular-nums;
    font-size: 11px;
    line-height: 16px;
  }
  .grid {
    width: 100%;
  }
  .row {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 8px;
    padding: 0 2px;
  }
  .alignCenter span {
    text-align: center;
  }
  .alignRight span {
    text-align: right;
  }
  .row span {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>

// packages/react/src/node-property-panel/virtual-values/virtual-values.tsx
import React, { useRef } from "react";
import { ScrollArea } from "@base-ui/react/scroll-area";
import { useVirtualizer } from "@tanstack/react-virtual";
import propertyPanelCss from "../node-property-panel.module.css";
import virtualValuesCss from "./virtual-values.module.css";

const ROW_HEIGHT = 16;
const COLS = 5;

type Values = Float64Array | Int32Array | BigInt64Array;

export function VirtualValues({
  values,
  format,
  align = "center",
  "data-testid": testId,
}: {
  values: Values;
  format: (v: number) => string;
  align?: "center" | "right";
  "data-testid"?: string;
}) {
  const parentRef = useRef<HTMLDivElement>(null);
  const totalRows = Math.ceil(values.length / COLS);

  const v = useVirtualizer({
    count: totalRows,
    getScrollElement: () => parentRef.current,
    estimateSize: () => ROW_HEIGHT,
    overscan: 6,
  });

  const alignClass = align === "right" ? virtualValuesCss.gridAlignRight : virtualValuesCss.gridAlignCenter;

  return (
    <ScrollArea.Root className={virtualValuesCss.valuesScrollRoot} data-testid={testId}>
      <ScrollArea.Viewport ref={parentRef} className={virtualValuesCss.valuesScrollViewport}>
        <ScrollArea.Content>
          <div className={virtualValuesCss.gridVals} style={{ height: v.getTotalSize(), position: "relative" }}>
            {v.getVirtualItems().map((row) => (
              <div
                key={row.index}
                className={`${virtualValuesCss.gridRow} ${alignClass}`}
                style={{ top: row.start, height: ROW_HEIGHT }}
              >
                {Array.from({ length: COLS }, (_, c) => {
                  const idx = row.index * COLS + c;
                  if (idx >= values.length) return <span key={c} />;
                  const raw = values[idx];
                  const num = typeof raw === "bigint" ? Number(raw) : raw;
                  return <span key={c}>{format(num)}</span>;
                })}
              </div>
            ))}
          </div>
        </ScrollArea.Content>
      </ScrollArea.Viewport>
      <ScrollArea.Scrollbar orientation="vertical" className={propertyPanelCss.scrollbar}>
        <ScrollArea.Thumb className={propertyPanelCss.scrollThumb} />
      </ScrollArea.Scrollbar>
    </ScrollArea.Root>
  );
}
