// packages/react/src/tooltip.tsx
import React, { useState } from "react";
import { createPortal } from "react-dom";

type Pos = { x: number; y: number };

const MAX_W = 280;
const OFFSET = 14;
const MARGIN = 8;

export function Tooltip({ text, children }: { text: string; children: React.ReactNode }) {
  const [pos, setPos] = useState<Pos | null>(null);

  return (
    <div
      style={{ display: "contents" }}
      onMouseEnter={(e) => setPos({ x: e.clientX, y: e.clientY })}
      onMouseMove={(e) => setPos({ x: e.clientX, y: e.clientY })}
      onMouseLeave={() => setPos(null)}
    >
      {children}
      {pos &&
        createPortal(
          <TooltipBox text={text} pos={pos} />,
          document.body,
        )}
    </div>
  );
}

function TooltipBox({ text, pos }: { text: string; pos: Pos }) {
  const wouldOverflow = pos.x + OFFSET + MAX_W > window.innerWidth - MARGIN;
  const left = wouldOverflow
    ? Math.max(MARGIN, pos.x - MAX_W - 6)
    : pos.x + OFFSET;
  const top = Math.min(pos.y - 10, window.innerHeight - 32);

  return (
    <div
      style={{
        position: "fixed",
        left,
        top,
        maxWidth: MAX_W,
        background: "#1e1e2e",
        color: "#e8e8f0",
        padding: "4px 8px",
        borderRadius: 4,
        fontSize: 11,
        fontFamily: "monospace",
        pointerEvents: "none",
        zIndex: 9999,
        wordBreak: "break-word",
        boxShadow: "0 2px 10px rgba(0,0,0,0.25)",
        lineHeight: 1.5,
      }}
    >
      {text}
    </div>
  );
}

// packages/svelte/src/tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    text: string;
    onlyIfOverflow?: boolean;
    children: Snippet;
  }

  let { text, onlyIfOverflow = false, children }: Props = $props();

  let wrapEl = $state<HTMLSpanElement | undefined>(undefined);
  let visible = $state(false);
  let disabled = $state(onlyIfOverflow);
  let px = $state(0);
  let py = $state(0);

  $effect(() => {
    if (!onlyIfOverflow || !wrapEl) return;
    const el = (wrapEl.firstElementChild as HTMLElement | null) ?? wrapEl;
    const check = () => { disabled = el.scrollWidth <= el.offsetWidth; };
    check();
    const ro = new ResizeObserver(check);
    ro.observe(el);
    return () => ro.disconnect();
  });

  function show() {
    if (disabled || !wrapEl) return;
    const el = (wrapEl.firstElementChild as HTMLElement | null) ?? wrapEl;
    const rect = el.getBoundingClientRect();
    px = rect.left;
    py = rect.bottom + 8;
    visible = true;
  }

  function hide() {
    visible = false;
  }

  function portal(node: HTMLElement): void {
    document.body.appendChild(node);
  }
</script>

<span
  bind:this={wrapEl}
  style="display: contents"
  onmouseenter={show}
  onmouseleave={hide}
>
  {@render children()}
</span>

{#if visible}
  <div use:portal role="tooltip" class="popup" style="left: {px}px; top: {py}px;">
    {text}
  </div>
{/if}

<style>
  .popup {
    position: fixed;
    z-index: 10000;
    max-width: 280px;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 11px;
    font-family: monospace;
    pointer-events: none;
    word-break: break-word;
    line-height: 1.5;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.25);
    background: var(--wetron-tooltip-bg, #1e1e2e);
    color: var(--wetron-tooltip-color, #e8e8f0);
  }
</style>
