// packages/react/src/node-property-panel/edge-panel.tsx
import React from "react";
import { ArrowsLeftRightIcon } from "@phosphor-icons/react";
import { Row, SectionLabel, BackButton } from "./panel-ui.tsx";
import css from "./node-property-panel.module.css";

type EdgeData = {
  tensorName: string;
  from: { opType: string; name: string };
  to: Array<{ opType: string; name: string }>;
};

type TensorInfo = { readonly shape: readonly number[] | null; readonly dtype: string | null };

export function EdgePanel({
  edge,
  tensorShapes,
  onBack,
}: {
  edge: EdgeData;
  tensorShapes?: ReadonlyMap<string, TensorInfo>;
  onBack?: () => void;
}) {
  const info = tensorShapes?.get(edge.tensorName);
  return (
    <>
      <div className={css.header}>
        {onBack && <BackButton onBack={onBack} />}
        <div className={css.iconBox} data-kind="edge">
          <ArrowsLeftRightIcon size={15} />
        </div>
        <div>
          <div className={css.nodeTitle}>Connection</div>
          <div className={css.nodeSubtitle} title={edge.tensorName}>
            {edge.tensorName}
          </div>
        </div>
      </div>
      {(info?.shape != null || info?.dtype) && (
        <div className={css.section}>
          {info?.shape != null && (
            <Row label="shape" value={`[${info.shape.join(", ")}]`} chip="int[]" />
          )}
          {info?.dtype && <Row label="dtype" value={info.dtype} chip="str" />}
        </div>
      )}
      <div className={css.section}>
        <SectionLabel icon={null} title="From" />
        <Row label={edge.from.opType} chip="str" value={edge.from.name} />
      </div>
      <div className={css.sectionLast}>
        <SectionLabel icon={null} title="To" />
        {edge.to.map((t, i) => (
          <Row key={`${i}-${t.opType}-${t.name}`} label={t.opType} chip="str" value={t.name} />
        ))}
      </div>
    </>
  );
}

// packages/svelte/src/node-property-panel/edge-panel.svelte
<script lang="ts">
  import { ArrowsLeftRightIcon } from 'phosphor-svelte';
  import Row from './row.svelte';
  import SectionLabel from './section-label.svelte';
  import PanelHeader from './panel-header.svelte';

  type EdgeData = {
    tensorName: string;
    from: { opType: string; name: string };
    to: Array<{ opType: string; name: string }>;
  };

  type TensorInfo = { readonly shape: readonly number[] | null; readonly dtype: string | null };

  let { edge, tensorShapes, onBack }: {
    edge: EdgeData;
    tensorShapes?: ReadonlyMap<string, TensorInfo>;
    onBack?: () => void;
  } = $props();

  const info = $derived(tensorShapes?.get(edge.tensorName));
  const hasInfo = $derived((info?.shape != null) || !!info?.dtype);
</script>

<PanelHeader title="Connection" subtitle={edge.tensorName} iconKind="edge" {onBack}>
  {#snippet icon()}<ArrowsLeftRightIcon size={15} />{/snippet}
</PanelHeader>
{#if hasInfo}
  <div class="section">
    {#if info?.shape != null}
      <Row label="shape" value={`[${info.shape.join(', ')}]`} chip="int[]" />
    {/if}
    {#if info?.dtype}
      <Row label="dtype" value={info.dtype} chip="str" />
    {/if}
  </div>
{/if}
<div class="section">
  <SectionLabel title="From" />
  <Row label={edge.from.opType} chip="str" value={edge.from.name} />
</div>
<div class="sectionLast">
  <SectionLabel title="To" />
  {#each edge.to as t, i (`${i}-${t.opType}-${t.name}`)}
    <Row label={t.opType} chip="str" value={t.name} />
  {/each}
</div>

<style>
  .section {
    padding: 7px 11px;
    border-bottom: 1px solid var(--panel-section-border);
  }
  .sectionLast { padding: 7px 11px; }
</style>
