// packages/react/src/node-property-panel/io-panel.tsx
import React from "react";
import { ArrowFatDownIcon, ArrowFatUpIcon } from "@phosphor-icons/react";
import type { GraphValue } from "@wetron/core/ir";
import { Row, BackButton } from "./panel-ui.tsx";
import css from "./node-property-panel.module.css";

export function IoPanel({
  graphValue,
  direction,
  onBack,
}: {
  graphValue: GraphValue;
  direction: "input" | "output";
  onBack?: () => void;
}) {
  const isInput = direction === "input";
  return (
    <>
      <div className={css.header}>
        {onBack && <BackButton onBack={onBack} />}
        <div className={css.iconBox} data-kind={direction}>
          {isInput ? <ArrowFatDownIcon size={15} /> : <ArrowFatUpIcon size={15} />}
        </div>
        <div>
          <div className={css.nodeTitle}>{graphValue.name}</div>
          <div className={css.nodeSubtitle}>{direction}</div>
        </div>
      </div>
      <div className={css.sectionLast}>
        {graphValue.shape !== null && (
          <Row label="shape" value={`[${graphValue.shape.join(" × ")}]`} chip="int[]" />
        )}
        {graphValue.dtype !== null && <Row label="dtype" value={graphValue.dtype} chip="str" />}
      </div>
    </>
  );
}

// packages/svelte/src/node-property-panel/io-panel.svelte
<script lang="ts">
  import { ArrowFatDownIcon, ArrowFatUpIcon } from 'phosphor-svelte';
  import type { GraphValue } from '@wetron/core/ir';
  import Row from './row.svelte';
  import PanelHeader from './panel-header.svelte';

  let { graphValue, direction, onBack }: {
    graphValue: GraphValue;
    direction: 'input' | 'output';
    onBack?: () => void;
  } = $props();

  const isInput = $derived(direction === 'input');
</script>

<PanelHeader title={graphValue.name} subtitle={direction} iconKind={direction} {onBack}>
  {#snippet icon()}
    {#if isInput}<ArrowFatDownIcon size={15} />{:else}<ArrowFatUpIcon size={15} />{/if}
  {/snippet}
</PanelHeader>
<div class="sectionLast">
  {#if graphValue.shape !== null}
    <Row label="shape" value={`[${graphValue.shape.join(' × ')}]`} chip="int[]" />
  {/if}
  {#if graphValue.dtype !== null}
    <Row label="dtype" value={graphValue.dtype} chip="str" />
  {/if}
</div>

<style>
  .sectionLast { padding: 7px 11px; }
</style>
