// packages/react/src/node-property-panel/node-property-panel.tsx
import React from "react";
import { ScrollArea } from "@base-ui/react/scroll-area";
import type { GraphNode, GraphValue, ModelGraph, PanelTarget } from "@wetron/core/ir";
import { useResolvedColorMode, type ColorMode } from "../color-mode-context.ts";
import { OpPanel } from "./op-panel.tsx";
import { IoPanel } from "./io-panel.tsx";
import { EdgePanel } from "./edge-panel.tsx";
import { TensorPanel } from "./tensor-panel.tsx";
import { WeightPanel } from "./weight-panel.tsx";
import { CloseButton } from "./panel-ui.tsx";
import css from "./node-property-panel.module.css";

export function isGraphNode(t: PanelTarget): t is GraphNode {
  return "opType" in t;
}

function isEdgeTarget(t: PanelTarget): t is {
  edge: {
    tensorName: string;
    from: { opType: string; name: string };
    to: Array<{ opType: string; name: string }>;
  };
} {
  return "edge" in t;
}

function isTensorTarget(
  t: PanelTarget,
): t is { tensor: { name: string; shape: readonly number[] | null; dtype: string | null } } {
  return "tensor" in t;
}

type TensorInfo = { readonly shape: readonly number[] | null; readonly dtype: string | null };

export function NodePropertyPanel({
  target,
  graph,
  onTensorClick,
  onBack,
  onClose,
  colorMode,
  inputSources,
  tensorShapes,
  opsets,
}: {
  target: PanelTarget | null;
  graph?: ModelGraph;
  onTensorClick?: (name: string) => void;
  onBack?: () => void;
  onClose?: () => void;
  colorMode?: ColorMode;
  inputSources?: ReadonlyMap<string, string>;
  tensorShapes?: ReadonlyMap<string, TensorInfo>;
  opsets?: ReadonlyMap<string, number>;
}) {
  const theme = useResolvedColorMode(colorMode ?? "system");
  const isDark = theme === "dark";

  if (!target) return null;
  return (
    <div className={css.panel} data-theme={theme}>
      {onClose && <CloseButton onClose={onClose} />}
      <ScrollArea.Root key={isGraphNode(target) ? target.name : "other"} className={css.scrollRoot}>
        <ScrollArea.Viewport className={css.scrollViewport}>
          <ScrollArea.Content>
            <div className={css.scrollContent}>
              {isGraphNode(target) ? (
                <OpPanel
                  node={target}
                  isDark={isDark}
                  inputSources={inputSources}
                  onTensorClick={onTensorClick}
                  onBack={onBack}
                  opsets={opsets}
                />
              ) : isEdgeTarget(target) ? (
                <EdgePanel edge={target.edge} tensorShapes={tensorShapes} onBack={onBack} />
              ) : isTensorTarget(target) ? (
                graph?.initializers.has(target.tensor.name) ? (
                  <WeightPanel target={target.tensor} graph={graph} onBack={onBack} />
                ) : (
                  <TensorPanel tensor={target.tensor} onBack={onBack} />
                )
              ) : (
                <IoPanel
                  graphValue={target.graphValue}
                  direction={target.direction}
                  onBack={onBack}
                />
              )}
            </div>
          </ScrollArea.Content>
        </ScrollArea.Viewport>
        <ScrollArea.Scrollbar orientation="vertical" className={css.scrollbar}>
          <ScrollArea.Thumb className={css.scrollThumb} />
        </ScrollArea.Scrollbar>
      </ScrollArea.Root>
    </div>
  );
}

// packages/svelte/src/node-property-panel/node-property-panel.svelte
<script lang="ts">
  import { resolveColorMode, type ColorMode } from '../color-mode-context.ts';
  import type { PanelTarget, GraphNode, GraphValue, ModelGraph } from '@wetron/core/ir';
  import { PANEL_VARS } from '@wetron/tokens';
  import { categoryVars } from '../category-vars.ts';
  import OpPanel from './op-panel.svelte';
  import IoPanel from './io-panel.svelte';
  import EdgePanel from './edge-panel.svelte';
  import TensorPanel from './tensor-panel.svelte';
  import WeightPanel from './weight-panel.svelte';
  import CloseButton from './close-button.svelte';

  type TensorInfo = { readonly shape: readonly number[] | null; readonly dtype: string | null };

  let { target, graph, onTensorClick, onBack, onClose, colorMode, inputSources, tensorShapes, opsets }: {
    target: PanelTarget | null;
    graph?: ModelGraph;
    onTensorClick?: (name: string) => void;
    onBack?: () => void;
    onClose?: () => void;
    colorMode?: ColorMode;
    inputSources?: ReadonlyMap<string, string>;
    tensorShapes?: ReadonlyMap<string, TensorInfo>;
    opsets?: ReadonlyMap<string, number>;
  } = $props();

  let systemIsDark = $state(resolveColorMode('system') === 'dark');

  $effect(() => {
    const mode = colorMode ?? 'system';
    if (mode !== 'system') return;
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    systemIsDark = mq.matches;
    const handler = (e: MediaQueryListEvent) => { systemIsDark = e.matches; };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  });

  const isDark = $derived(
    (colorMode ?? 'system') === 'dark' ? true :
    (colorMode ?? 'system') === 'light' ? false :
    systemIsDark
  );
  const theme = $derived(isDark ? 'dark' : 'light');

  function isGraphNode(t: PanelTarget): t is GraphNode {
    return 'opType' in t;
  }
  function isEdgeTarget(t: PanelTarget): t is { edge: { tensorName: string; from: { opType: string; name: string }; to: Array<{ opType: string; name: string }> } } {
    return 'edge' in t;
  }
  function isTensorTarget(t: PanelTarget): t is { tensor: { name: string; shape: readonly number[] | null; dtype: string | null } } {
    return 'tensor' in t;
  }
  function isIoTarget(t: PanelTarget): t is { graphValue: GraphValue; direction: 'input' | 'output' } {
    return 'graphValue' in t;
  }
</script>

{#if target}
  <div
    class="panel"
    data-theme={theme}
    style={[
      ...Object.entries(PANEL_VARS[isDark ? 'dark' : 'light']),
      ...Object.entries(categoryVars(isDark)),
    ].map(([k, v]) => `${k}:${v}`).join(';')}
  >
    {#if onClose}<CloseButton {onClose} />{/if}
    {#if isGraphNode(target)}
      <OpPanel node={target} {inputSources} {onTensorClick} {onBack} {opsets} />
    {:else if isEdgeTarget(target)}
      <EdgePanel edge={target.edge} {tensorShapes} {onBack} />
    {:else if isTensorTarget(target)}
      {#if graph?.initializers.has(target.tensor.name)}
        <WeightPanel target={target.tensor} {graph} {onBack} {isDark} />
      {:else}
        <TensorPanel tensor={target.tensor} {onBack} />
      {/if}
    {:else if isIoTarget(target)}
      <IoPanel graphValue={target.graphValue} direction={target.direction} {onBack} />
    {/if}
  </div>
{/if}

<style>
  .panel {
    position: relative;
    width: 320px;
    background: var(--panel-bg);
    border-radius: 8px;
    overflow: hidden;
    font-family: system-ui, sans-serif;
    font-size: 11px;
    border: 1px solid var(--panel-border);
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.10);
    color: var(--panel-text);
  }

</style>
