// packages/react/src/node-property-panel/inspectors/sparsity-inspector.tsx
import { useMemo, useState } from 'react';
import { computeSparsityBlocks, computeWeightSparsity } from '@wetron/core/weight-sparsity';
import {
  axisOptionLabel,
  matrixAxisHint,
  sparsityBlockHint,
  sparsityDeadHint,
  sparsityModeHint,
  sparsityZeroHint,
} from '@wetron/core/inspector-hints';
import { useWeightInspection } from '../weight-inspection-context.tsx';
import { Hint } from './hint.tsx';
import css from './inspectors.module.css';

export function SparsityInspector() {
  const inspection = useWeightInspection();
  const shape = inspection.tensor.shape;
  const [near, setNear] = useState(false);
  const [threshold, setThreshold] = useState(0.001);
  const [rowAxis, setRowAxis] = useState(Math.max(0, (shape?.length ?? 2) - 2));
  const [colAxis, setColAxis] = useState(Math.max(1, (shape?.length ?? 2) - 1));
  const [fixed, setFixed] = useState<Record<number, number>>(() =>
    Object.fromEntries((shape ?? []).map((_, axis) => [axis, 0])),
  );
  const effectiveThreshold = near ? threshold : 0;
  const result = useMemo(
    () =>
      inspection.status === 'ready' && shape
        ? computeWeightSparsity(
            inspection.values,
            shape,
            shape.length ? Math.min(rowAxis, shape.length - 1) : 0,
            effectiveThreshold,
          )
        : null,
    [inspection, shape, rowAxis, effectiveThreshold],
  );
  const blockRows = shape && shape.length >= 2 ? Math.max(1, Math.ceil(shape[rowAxis] / 4)) : 1;
  const blockCols = shape && shape.length >= 2 ? Math.max(1, Math.ceil(shape[colAxis] / 4)) : 1;
  const blocks = useMemo(
    () =>
      inspection.status === 'ready' && shape && shape.length >= 2
        ? computeSparsityBlocks(
            inspection.values,
            shape,
            { rowAxis, colAxis, fixed },
            blockRows,
            blockCols,
            effectiveThreshold,
          )
        : [],
    [inspection, shape, rowAxis, colAxis, fixed, effectiveThreshold, blockRows, blockCols],
  );
  if (!result || inspection.status !== 'ready' || !shape) return null;
  const setAxis = (kind: 'row' | 'col', axis: number) => {
    if (kind === 'row') {
      setRowAxis(axis);
      if (axis === colAxis) setColAxis(rowAxis);
    } else {
      setColAxis(axis);
      if (axis === rowAxis) setRowAxis(colAxis);
    }
  };
  return (
    <div className={css.root} data-testid="sparsity-inspector">
      <div className={css.controls}>
        <div className={css.control}>
          <span className={css.caption}>
            mode <Hint text={sparsityModeHint()} />
          </span>
          <select
            className={css.field}
            aria-label="Sparsity mode"
            value={near ? 'near' : 'exact'}
            onChange={(event) => setNear(event.target.value === 'near')}
          >
            <option value="exact">exact zero</option>
            <option value="near">near zero</option>
          </select>
        </div>
        {near && (
          <div className={css.control}>
            <span className={css.caption}>threshold</span>
            <input
              className={css.field}
              aria-label="Sparsity threshold"
              type="number"
              min="0"
              step="0.001"
              value={threshold}
              onChange={(event) => setThreshold(Math.max(0, Number(event.target.value)))}
            />
          </div>
        )}
        {shape.length >= 2 && (
          <>
            <div className={css.control}>
              <span className={css.caption}>
                rows <Hint text={matrixAxisHint('row')} />
              </span>
              <select
                className={css.field}
                aria-label="Sparsity row axis"
                value={rowAxis}
                onChange={(event) => setAxis('row', Number(event.target.value))}
              >
                {shape.map((_, axis) => (
                  <option key={axis} value={axis}>
                    {axisOptionLabel(axis, shape)}
                  </option>
                ))}
              </select>
            </div>
            <div className={css.control}>
              <span className={css.caption}>
                cols <Hint text={matrixAxisHint('col')} />
              </span>
              <select
                className={css.field}
                aria-label="Sparsity column axis"
                value={colAxis}
                onChange={(event) => setAxis('col', Number(event.target.value))}
              >
                {shape.map((_, axis) => (
                  <option key={axis} value={axis}>
                    {axisOptionLabel(axis, shape)}
                  </option>
                ))}
              </select>
            </div>
            {shape.map(
              (dimension, axis) =>
                axis !== rowAxis &&
                axis !== colAxis && (
                  <div className={css.control} key={axis}>
                    <span className={css.caption}>axis {axis}</span>
                    <input
                      className={css.field}
                      aria-label={`Sparsity fixed axis ${axis}`}
                      type="number"
                      min={0}
                      max={dimension - 1}
                      value={fixed[axis] ?? 0}
                      onChange={(event) =>
                        setFixed((current) => ({
                          ...current,
                          [axis]: Math.max(0, Math.min(dimension - 1, Number(event.target.value))),
                        }))
                      }
                    />
                  </div>
                ),
            )}
          </>
        )}
      </div>
      <div className={css.summary}>
        <div className={css.summaryItem}>
          <span className={css.summaryValue}>{(result.zeroRatio * 100).toFixed(2)}%</span>
          <span className={css.summaryLabel}>
            zero values <Hint text={sparsityZeroHint(result, inspection.tensor.dtype)} />
          </span>
        </div>
        <div className={css.summaryItem}>
          <span className={css.summaryValue}>{result.deadSlices}</span>
          <span className={css.summaryLabel}>
            dead slices <Hint text={sparsityDeadHint(result, Math.min(rowAxis, shape.length - 1))} />
          </span>
        </div>
      </div>
      {shape.length >= 2 && (
        <>
          <div className={css.blockMap}>
            {blocks.map((block, index) => {
              const total = block.occupied + block.empty;
              const state = block.occupied === 0 ? 'empty' : block.empty === 0 ? 'full' : 'partial';
              return (
                <span
                  key={index}
                  aria-label={`${state} block`}
                  className={`${css.block} ${css[state]}`}
                  title={`coordinates [${block.coordinateStart.join(', ')}]…[${block.coordinateEnd.join(', ')}] · ${block.occupied}/${total} occupied`}
                />
              );
            })}
          </div>
          <div className={css.legend}>
            <span>
              <i className={css.empty} />
              empty
            </span>
            <span>
              <i className={css.partial} />
              partial
            </span>
            <span>
              <i className={css.full} />
              occupied
            </span>
            <Hint text={sparsityBlockHint(blockRows, blockCols)} />
          </div>
        </>
      )}
    </div>
  );
}

// packages/svelte/src/node-property-panel/sparsity-inspector.svelte
<script lang="ts">
    import { untrack } from 'svelte';
    import { computeSparsityBlocks, computeWeightSparsity } from '@wetron/core/weight-sparsity';
    import {
        axisOptionLabel,
        matrixAxisHint,
        sparsityBlockHint,
        sparsityDeadHint,
        sparsityModeHint,
        sparsityZeroHint,
    } from '@wetron/core/inspector-hints';
    import { getWeightInspection } from './weight-inspection-context.ts';
    import Hint from './hint.svelte';
    import './inspectors.css';
    const context = getWeightInspection();
    const ready = $derived(context.current.status === 'ready' ? context.current : null);
    const shape = $derived(ready?.tensor.shape ?? null);
    let near = $state(false);
    let threshold = $state(0.001);
    let rowAxis = $state(untrack(() => Math.max(0, (shape?.length ?? 2) - 2)));
    let colAxis = $state(untrack(() => Math.max(1, (shape?.length ?? 2) - 1)));
    let fixed = $state<Record<number, number>>(
        untrack(() => Object.fromEntries((shape ?? []).map((_, axis) => [axis, 0]))),
    );
    const effective = $derived(near ? threshold : 0);
    const blockRows = $derived(shape && shape.length >= 2 ? Math.max(1, Math.ceil(shape[rowAxis] / 4)) : 1);
    const blockCols = $derived(shape && shape.length >= 2 ? Math.max(1, Math.ceil(shape[colAxis] / 4)) : 1);
    const result = $derived(
        ready && shape
            ? computeWeightSparsity(
                  ready.values,
                  shape,
                  shape.length ? Math.min(rowAxis, shape.length - 1) : 0,
                  effective,
              )
            : null,
    );
    const blocks = $derived(
        ready && shape && shape.length >= 2
            ? computeSparsityBlocks(ready.values, shape, { rowAxis, colAxis, fixed }, blockRows, blockCols, effective)
            : [],
    );
    function setAxis(kind: 'row' | 'col', axis: number) {
        if (kind === 'row') {
            const previous = rowAxis;
            rowAxis = axis;
            if (axis === colAxis) colAxis = previous;
        } else {
            const previous = colAxis;
            colAxis = axis;
            if (axis === rowAxis) rowAxis = previous;
        }
    }
</script>

{#if ready && shape && result}<div class="inspector" data-testid="sparsity-inspector">
        <div class="inspector-controls">
            <div class="inspector-control">
                <span class="inspector-caption">mode <Hint text={sparsityModeHint()} /></span><select
                    class="inspector-field"
                    aria-label="Sparsity mode"
                    value={near ? 'near' : 'exact'}
                    onchange={(event) => (near = event.currentTarget.value === 'near')}
                    ><option value="exact">exact zero</option><option value="near">near zero</option></select
                >
            </div>
            {#if near}<div class="inspector-control">
                    <span class="inspector-caption">threshold</span><input
                        class="inspector-field"
                        aria-label="Sparsity threshold"
                        type="number"
                        min="0"
                        step="0.001"
                        bind:value={threshold}
                    />
                </div>{/if}{#if shape.length >= 2}<div class="inspector-control">
                    <span class="inspector-caption">rows <Hint text={matrixAxisHint('row')} /></span><select
                        class="inspector-field"
                        aria-label="Sparsity row axis"
                        value={rowAxis}
                        onchange={(event) => setAxis('row', Number(event.currentTarget.value))}
                        >{#each shape as _, axis}<option value={axis}>{axisOptionLabel(axis, shape)}</option
                            >{/each}</select
                    >
                </div>
                <div class="inspector-control">
                    <span class="inspector-caption">cols <Hint text={matrixAxisHint('col')} /></span><select
                        class="inspector-field"
                        aria-label="Sparsity column axis"
                        value={colAxis}
                        onchange={(event) => setAxis('col', Number(event.currentTarget.value))}
                        >{#each shape as _, axis}<option value={axis}>{axisOptionLabel(axis, shape)}</option
                            >{/each}</select
                    >
                </div>
                {#each shape as dimension, axis}{#if axis !== rowAxis && axis !== colAxis}<div
                            class="inspector-control"
                        >
                            <span class="inspector-caption">axis {axis}</span><input
                                class="inspector-field"
                                aria-label="Sparsity fixed axis {axis}"
                                type="number"
                                min="0"
                                max={dimension - 1}
                                value={fixed[axis] ?? 0}
                                oninput={(event) =>
                                    (fixed = {
                                        ...fixed,
                                        [axis]: Math.max(0, Math.min(dimension - 1, Number(event.currentTarget.value))),
                                    })}
                            />
                        </div>{/if}{/each}{/if}
        </div>
        <div class="inspector-summary">
            <div class="inspector-summary-item">
                <span class="inspector-summary-value">{(result.zeroRatio * 100).toFixed(2)}%</span><span
                    class="inspector-summary-label"
                    >zero values <Hint text={sparsityZeroHint(result, ready.tensor.dtype)} /></span
                >
            </div>
            <div class="inspector-summary-item">
                <span class="inspector-summary-value">{result.deadSlices}</span><span class="inspector-summary-label"
                    >dead slices <Hint text={sparsityDeadHint(result, Math.min(rowAxis, shape.length - 1))} /></span
                >
            </div>
        </div>
        {#if shape.length >= 2}<div class="inspector-block-map">
                {#each blocks as block}{@const state =
                        block.occupied === 0 ? 'empty' : block.empty === 0 ? 'full' : 'partial'}<span
                        aria-label="{state} block"
                        class="inspector-block inspector-{state}"
                        title="coordinates [{block.coordinateStart.join(', ')}]…[{block.coordinateEnd.join(
                            ', ',
                        )}] · {block.occupied}/{block.occupied + block.empty} occupied"
                    ></span>{/each}
            </div>
            <div class="inspector-legend">
                <span><i class="inspector-empty"></i>empty</span><span><i class="inspector-partial"></i>partial</span
                ><span><i class="inspector-full"></i>occupied</span><Hint
                    text={sparsityBlockHint(blockRows, blockCols)}
                />
            </div>{/if}
    </div>{/if}
