// packages/react/src/node-property-panel/tensor-panel.tsx
import React from "react";
import { CubeIcon } from "@phosphor-icons/react";
import { Row, BackButton } from "./panel-ui.tsx";
import css from "./node-property-panel.module.css";

export function TensorPanel({
  tensor,
  onBack,
}: {
  tensor: { name: string; shape: readonly number[] | null; dtype: string | null };
  onBack?: () => void;
}) {
  const hasInfo = tensor.shape !== null || tensor.dtype !== null;
  return (
    <>
      <div className={css.header}>
        {onBack && <BackButton onBack={onBack} />}
        <div className={css.iconBox} data-kind="tensor">
          <CubeIcon size={15} />
        </div>
        <div style={{ minWidth: 0, flex: 1, overflow: "hidden" }}>
          <div className={css.nodeTitle}>Tensor</div>
          <div className={css.nodeSubtitle} title={tensor.name}>
            {tensor.name}
          </div>
        </div>
      </div>
      {hasInfo && (
        <div className={css.sectionLast}>
          {tensor.shape !== null && (
            <Row label="shape" value={`[${tensor.shape.join(" × ")}]`} chip="int[]" />
          )}
          {tensor.dtype !== null && <Row label="dtype" value={tensor.dtype} chip="str" />}
        </div>
      )}
    </>
  );
}

// packages/svelte/src/node-property-panel/tensor-panel.svelte
<script lang="ts">
  import { CubeIcon } from 'phosphor-svelte';
  import Row from './row.svelte';
  import PanelHeader from './panel-header.svelte';

  let {
    tensor,
    onBack,
  }: {
    tensor: { name: string; shape: readonly number[] | null; dtype: string | null };
    onBack?: () => void;
  } = $props();

  const hasInfo = $derived(tensor.shape !== null || tensor.dtype !== null);
</script>

<PanelHeader title="Tensor" subtitle={tensor.name} iconKind="tensor" {onBack}>
  {#snippet icon()}<CubeIcon size={15} />{/snippet}
</PanelHeader>
{#if hasInfo}
  <div class="sectionLast">
    {#if tensor.shape !== null}
      <Row label="shape" value={`[${tensor.shape.join(' × ')}]`} chip="int[]" />
    {/if}
    {#if tensor.dtype !== null}
      <Row label="dtype" value={tensor.dtype} chip="str" />
    {/if}
  </div>
{/if}

<style>
  .sectionLast {
    padding: 7px 11px;
  }
</style>
