// packages/svelte/src/model-graph-view.svelte
<script lang="ts">
  import { SvelteFlow, MiniMap, Controls, Background } from '@xyflow/svelte';
  import FitViewHelper from './fit-view-helper.svelte';
  import '@xyflow/svelte/dist/style.css';
  import { setContext } from 'svelte';
  import { modelGraphToFlow } from '@wetron/core/transform';
  import type { ModelGraph } from '@wetron/core/ir';
  import type { GraphNodeData } from '@wetron/core/transform';
  import GraphNodeComponent from './nodes/graph-node.svelte';
  import IoNodeComponent from './nodes/io-node.svelte';
  import { provideColorMode, resolveColorMode, type ColorMode } from './color-mode-context.ts';
  import type { PanelTarget } from './types.ts';
  import { CANVAS_VARS, MINIMAP_THEME, EDGE_THEME } from '@wetron/tokens';

  type FlowEdgeData = {
    tensorName: string;
    sourceOpType: string;
    sourceNodeName: string;
    targetOpType: string;
    targetNodeName: string;
  };

  interface Props {
    graph: ModelGraph;
    onTargetClick?: (target: PanelTarget) => void;
    selectedEdgeTensorName?: string | null;
    colorMode?: ColorMode;
  }

  let { graph, onTargetClick, selectedEdgeTensorName = null, colorMode = 'system' }: Props = $props();

  provideColorMode(colorMode);
  setContext('wetron:onTargetClick', () => onTargetClick);

  const isDark = $derived(resolveColorMode(colorMode) === 'dark');

  const nodeTypes = {
    graphNode: GraphNodeComponent,
    ioNode: IoNodeComponent,
  };

  const edgeDefaults = $derived(
    isDark
      ? { style: 'stroke: #7a7a9a; opacity: 0.55;' }
      : { style: 'opacity: 0.35;' }
  );

  const rawFlow = $derived(modelGraphToFlow(graph));

  // $state.raw prevents @xyflow/svelte from seeing deeply-reactive proxies;
  // it mutates node objects internally (computed dims/positions) and that would
  // write back through Svelte's proxy, invalidating rawFlow → infinite loop.
  let flowNodes = $state.raw(rawFlow.nodes);
  $effect.pre(() => {
    flowNodes = rawFlow.nodes;
  });

  const flowEdges = $derived(rawFlow.edges.map(edge => {
    const tensorName = (edge.data as FlowEdgeData | undefined)?.tensorName;
    const isSelected = selectedEdgeTensorName != null && tensorName === selectedEdgeTensorName;
    const anySelected = selectedEdgeTensorName != null;
    return {
      ...edge,
      style: isSelected
        ? `stroke: ${EDGE_THEME.selectedStroke}; stroke-width: ${EDGE_THEME.selectedStrokeWidth}; opacity: 1;`
        : anySelected
          ? `stroke: ${isDark ? 'rgba(120,120,160,0.2)' : 'rgba(0,0,0,0.1)'}; opacity: 1;`
          : edgeDefaults.style,
    };
  }));

  function handleNodeClick({ node, event }: { node: { data: GraphNodeData }; event: MouseEvent | TouchEvent }) {
    if (!onTargetClick) return;
    const weightRow = (event.target as Element).closest('[data-weight-name]') as HTMLElement | null;
    if (weightRow) {
      const name = weightRow.dataset.weightName;
      const shapeStr = weightRow.dataset.weightShape;
      if (name && shapeStr) {
        onTargetClick({ tensor: { name, shape: shapeStr.split(',').map(Number), dtype: weightRow.dataset.weightDtype ?? null } });
      }
      return;
    }
    if (node.data.graphNode) {
      onTargetClick(node.data.graphNode);
    } else if (node.data.graphValue) {
      onTargetClick({ graphValue: node.data.graphValue, direction: node.data.opType === 'Input' ? 'input' : 'output' });
    }
  }

  function handleEdgeClick({ edge }: { edge: { data?: FlowEdgeData }; event: MouseEvent }) {
    if (!onTargetClick || !edge.data) return;
    const d = edge.data;
    const sameEdges = rawFlow.edges.filter(e => (e.data as FlowEdgeData | undefined)?.tensorName === d.tensorName);
    const from = { opType: d.sourceOpType, name: d.sourceNodeName };
    const to = sameEdges.map(e => ({ opType: (e.data as FlowEdgeData).targetOpType, name: (e.data as FlowEdgeData).targetNodeName }));
    onTargetClick({ edge: { tensorName: d.tensorName, from, to } });
  }
</script>

<div
  class="wetron-graph"
  data-theme={isDark ? 'dark' : 'light'}
  style={Object.entries(CANVAS_VARS[isDark ? 'dark' : 'light']).map(([k, v]) => `${k}:${v}`).join(';')}
>
  <SvelteFlow
    nodes={flowNodes}
    edges={flowEdges}
    {nodeTypes}
    onnodeclick={handleNodeClick}
    onedgeclick={handleEdgeClick}
    panOnScroll
    zoomOnScroll={false}
    zoomOnDoubleClick={false}
    zoomActivationKey="Meta"
    minZoom={0.05}
    colorMode={isDark ? 'dark' : 'light'}
    proOptions={{ hideAttribution: true }}
  >
    <MiniMap
      style={`background: ${isDark ? MINIMAP_THEME.dark.background : MINIMAP_THEME.light.background}; border-radius: ${MINIMAP_THEME.borderRadius}px; border: none; overflow: hidden;`}
      nodeColor={isDark ? MINIMAP_THEME.dark.nodeColor : MINIMAP_THEME.light.nodeColor}
      maskColor={isDark ? MINIMAP_THEME.dark.maskColor : MINIMAP_THEME.light.maskColor}
    />
    <Controls />
    <Background bgColor={isDark ? '#2a2a3a' : '#d0d0d8'} />
    <FitViewHelper nodes={flowNodes} />
  </SvelteFlow>
</div>

<style>
  .wetron-graph {
    width: 100%;
    height: 100%;
  }

  /* ── Handles ── */
  :global(.wetron-graph .svelte-flow__handle) {
    width: 6px;
    height: 6px;
    min-width: 6px;
    min-height: 6px;
  }

  /* ── Controls ── */
  :global(.wetron-graph .svelte-flow__controls) {
    box-shadow: none;
    display: flex;
    flex-direction: column;
    gap: 3px;
  }

  :global(.wetron-graph .svelte-flow__controls-button) {
    border-radius: 4px;
    border-bottom: none;
  }

  /* ── Dark theme ── */
  :global(.wetron-graph[data-theme="dark"] .svelte-flow) {
    background-color: #13131f;
  }

  :global(.wetron-graph[data-theme="dark"] .svelte-flow__controls-button) {
    background-color: #1e1e2e;
    border-color: #2a2a3a;
    color: #7a7a9a;
  }

  :global(.wetron-graph[data-theme="dark"] .svelte-flow__controls-button:hover) {
    background-color: #252538;
    color: #a0a0c0;
  }

  :global(.wetron-graph[data-theme="dark"] .svelte-flow__controls-button svg) {
    fill: #7a7a9a;
  }

  :global(.wetron-graph[data-theme="dark"] .svelte-flow__controls-button:hover svg) {
    fill: #a0a0c0;
  }

  /* ── Light theme ── */
  :global(.wetron-graph[data-theme="light"] .svelte-flow) {
    background-color: #f8f8fc;
  }

  :global(.wetron-graph[data-theme="light"] .svelte-flow__controls-button) {
    background-color: #ffffff;
    border-color: #e0e0e0;
    color: #555;
  }

  :global(.wetron-graph[data-theme="light"] .svelte-flow__controls-button:hover) {
    background-color: #f0f0f8;
    color: #333;
  }

  /* ── Node defaults — remove XY Flow's default border/shadow on nodes ── */
  :global(.wetron-graph .svelte-flow__node) {
    border: none;
    border-radius: 0;
    box-shadow: none;
    background: transparent;
    padding: 0;
    font-size: inherit;
  }
</style>

// packages/react/src/model-graph-view/model-graph-view.tsx
import React, { useCallback, useMemo, useEffect } from "react";
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  ReactFlowProvider,
  useReactFlow,
  useNodesState,
  MarkerType,
  PanOnScrollMode,
  type Node,
  type Edge,
  type NodeMouseHandler,
  type NodeTypes,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import "./model-graph-view.css";
import { modelGraphToFlow, type GraphNodeData } from "@wetron/core/transform";
import type { ModelGraph } from "@wetron/core/ir";
import { GraphNodeComponent } from "../nodes/graph-node.tsx";
import { IoNodeComponent } from "../nodes/io-node.tsx";
import { type PanelTarget } from "../node-property-panel/node-property-panel.tsx";
import { ColorModeContext, useColorMode, type ColorMode } from "../color-mode-context.ts";
import { MINIMAP_THEME, EDGE_THEME } from "../theme.ts";

const nodeTypes: NodeTypes = {
  graphNode: GraphNodeComponent as NodeTypes[string],
  ioNode: IoNodeComponent as NodeTypes[string],
};

type FlowEdgeData = {
  tensorName: string;
  sourceOpType: string;
  sourceNodeName: string;
  targetOpType: string;
  targetNodeName: string;
};

type Props = {
  graph: ModelGraph;
  onTargetClick?: (target: PanelTarget) => void;
  colorMode?: ColorMode;
  selectedEdgeTensorName?: string | null;
};

function Inner({ graph, onTargetClick, selectedEdgeTensorName, colorMode }: Props) {
  const { fitView } = useReactFlow();
  const isDark = useColorMode() === "dark";
  const edgeDefaults = useMemo(
    () => (isDark ? { stroke: "#7a7a9a", opacity: 0.55 } : { stroke: "rgba(60,60,100,0.55)" }),
    [isDark],
  );
  const { nodes: layoutNodes, edges: layoutEdges } = useMemo(
    () => modelGraphToFlow(graph),
    [graph],
  );
  const [nodes, setNodes, onNodesChange] = useNodesState(layoutNodes as Node<GraphNodeData>[]);
  useEffect(() => {
    setNodes(layoutNodes as Node<GraphNodeData>[]);
  }, [layoutNodes, setNodes]);

  const edges = useMemo(
    () =>
      layoutEdges.map((e) => {
        const d = e.data as FlowEdgeData | undefined;
        if (d?.tensorName === selectedEdgeTensorName) {
          return {
            ...e,
            style: {
              stroke: EDGE_THEME.selectedStroke,
              strokeWidth: EDGE_THEME.selectedStrokeWidth,
              opacity: 1,
            },
            markerEnd: {
              type: MarkerType.ArrowClosed,
              color: EDGE_THEME.selectedStroke,
              width: 10,
              height: 10,
            },
          };
        }
        return e;
      }),
    [layoutEdges, selectedEdgeTensorName],
  );

  const handleNodeClick = useCallback<NodeMouseHandler<Node<GraphNodeData>>>(
    (event, node) => {
      if (!onTargetClick) return;
      const weightRow = (event.target as Element).closest(
        "[data-weight-name]",
      ) as HTMLElement | null;
      if (weightRow) {
        const name = weightRow.dataset.weightName;
        const shapeStr = weightRow.dataset.weightShape;
        if (name && shapeStr) {
          onTargetClick({
            tensor: {
              name,
              shape: shapeStr.split(",").map(Number),
              dtype: weightRow.dataset.weightDtype ?? null,
            },
          });
        }
        return;
      }
      if (node.data.graphNode) {
        onTargetClick(node.data.graphNode);
      } else if (node.data.graphValue) {
        onTargetClick({
          graphValue: node.data.graphValue,
          direction: node.data.opType === "Input" ? "input" : "output",
        });
      }
    },
    [onTargetClick],
  );

  const handleEdgeClick = useCallback(
    (_event: React.MouseEvent, edge: Edge) => {
      if (!onTargetClick || !edge.data) return;
      const d = edge.data as FlowEdgeData;
      const sameEdges = layoutEdges.filter(
        (e) => (e.data as FlowEdgeData | undefined)?.tensorName === d.tensorName,
      );
      const from = { opType: d.sourceOpType, name: d.sourceNodeName };
      const to = sameEdges.map((e) => ({
        opType: (e.data as FlowEdgeData).targetOpType,
        name: (e.data as FlowEdgeData).targetNodeName,
      }));
      onTargetClick({ edge: { tensorName: d.tensorName, from, to } });
    },
    [onTargetClick, layoutEdges],
  );

  React.useEffect(() => {
    const TARGET = 12;
    if (layoutNodes.length <= TARGET) {
      fitView({ maxZoom: 1, padding: 0.15 });
    } else {
      // For large graphs: fit to the topmost TARGET nodes so the view starts
      // at the inputs at a readable zoom rather than showing the whole graph
      const topNodes = [...layoutNodes]
        .sort((a, b) => a.position.y - b.position.y)
        .slice(0, TARGET)
        .map((n) => ({ id: n.id }));
      fitView({ nodes: topNodes, maxZoom: 1, padding: 0.15 });
    }
  }, [graph, fitView, layoutNodes]);

  return (
    <div data-theme={isDark ? "dark" : "light"} style={{ width: "100%", height: "100%" }}>
      <ReactFlow
        colorMode={colorMode}
        nodes={nodes}
        onNodesChange={onNodesChange}
        edges={edges}
        nodeTypes={nodeTypes}
        onNodeClick={handleNodeClick}
        onEdgeClick={handleEdgeClick}
        defaultEdgeOptions={{
          markerEnd: { type: MarkerType.ArrowClosed, width: 10, height: 10 },
          style: edgeDefaults,
        }}
        panOnScroll
        panOnScrollMode={PanOnScrollMode.Free}
        zoomOnScroll={false}
        zoomOnDoubleClick={false}
        zoomActivationKeyCode="Meta"
        minZoom={0.05}
        defaultViewport={{ x: 0, y: 0, zoom: 1 }}
        proOptions={{ hideAttribution: true }}
      >
        <MiniMap
          style={{
            background: isDark ? MINIMAP_THEME.dark.background : MINIMAP_THEME.light.background,
            borderRadius: MINIMAP_THEME.borderRadius,
            border: "none",
            overflow: "hidden",
          }}
          nodeColor={isDark ? MINIMAP_THEME.dark.nodeColor : MINIMAP_THEME.light.nodeColor}
          maskColor={isDark ? MINIMAP_THEME.dark.maskColor : MINIMAP_THEME.light.maskColor}
        />
        <Controls />
        <Background color={isDark ? "#2a2a3a" : "#d0d0d8"} />
      </ReactFlow>
    </div>
  );
}

export function ModelGraphView({ colorMode = "system", ...rest }: Props) {
  return (
    <ColorModeContext.Provider value={colorMode}>
      <ReactFlowProvider>
        <Inner {...rest} colorMode={colorMode} />
      </ReactFlowProvider>
    </ColorModeContext.Provider>
  );
}
